#!/bin/sh
#
# air quality sensor startup script for host piz
#
# on piz2, AQ sensor MQ9, DHT22 and buzzer with 
# status leds green (26), yellow (13) and red (16).
#
$PIHOME/python/aq_hat.py \
    --sensor-info=$PIHOME/config/sensor_info.json \
    --display=ssd1306 --width=128 --height=64 \
    --sensor mq9 --adc-addr 0x48 \
    --buzzer-type=passive --buzzer-pin=25 \
    --dht-type=22 --dht-pin=4 \
    --led-brightness=100 12 26 13 16 
