#!/bin/sh
#
# air quality sensor startup script for host piz
#
# on piz, AQ sensor MQ5, DHT11 and no buzzer with only
# status leds green (13) and red (26)
#
$PIHOME/python/aq_hat.py \
    --sensor-info=$PIHOME/config/sensor_info.json \
    --display=ssd1306 --width=128 --height=32 \
    --sensor mq5 --adc-addr 0x48 \
    --buzzer-type=none --buzzer-pin=20 \
    --dht11-pin=4 \
    --led-brightness=2 12 13 16 26 
