#!/bin/sh
#
# audio_viz_luma for an ili9341
#

# for audio injector hat (on audio-id=2), also set/adjust:
#   % amixer sset 'Input Mux' 'Mic'
#   % amixer sset 'Mic' toggle
#   % amixer sset 'Mic' 300
#
$PIHOME/python/audio_viz_luma.py --device=ili9341 --cascaded=4 --block-orientation=90 --reverse-order=True --audio-id=2 --sample-rate=12000 --color=yellow 320 240

# for pluggable usb device (on audio-id 0), with sensitivity adjustments:
#   % amixer sset 'Mic Boost' 1
#
#$PIHOME/python/audio_viz_luma.py --device=ili9341 --cascaded=4 --block-orientation=90 --reverse-order=True --audio-id=0 --sample-rate=48000 --color=yellow 320 240
