#!/bin/sh
#
# led_swarm_swarm with parameters for a ssd1306 display (128x64).
#
# Use higher x than y peak velocity, and 10 animated cells
#
$PIHOME/python/led_swarm_luma.py --device=ssd1306 --delay=0 -mvx 6 -mvy 3 128 64 10
